steps:
  # Build Next.js app with environment variables
  - name: 'node:18'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        export NEXT_PUBLIC_API_URL=https://deer-flow-api-57468802745.us-central1.run.app/api
        npm install
        npm run build
  
  # Build Docker image WITH build arg
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/ucan-deerflow/deer-flow-web'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=https://deer-flow-api-57468802745.us-central1.run.app/api'
      - '.'
  
  # Push the image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/ucan-deerflow/deer-flow-web'
  
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'deer-flow-web'
      - '--image'
      - 'gcr.io/ucan-deerflow/deer-flow-web'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--port'
      - '3000'
      - '--memory'
      - '4Gi'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NEXT_PUBLIC_API_URL=https://deer-flow-api-57468802745.us-central1.run.app/api'

options:
  machineType: 'E2_HIGHCPU_8'